name: Python Lint and Format with PEP8 and Google Docstrings

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Replace with your Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black

    # Step 4: Run Ruff for PEP8 and docstring checks
    - name: Run Ruff Lint
      run: |
        ruff check . --select E,F --extend-select D --ignore D203

    # Step 5: Run Black for formatting
    - name: Run Black Formatter
      run: |
        # Auto-format the code
        black .

    # Step 6: Cache pip dependencies (Optional)
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 7: Fail if formatting/linting issues remain
    - name: Ensure no issues remain
      run: |
        ruff . --select E,F --extend-select D --ignore D203
        black --check .
