name: Python Lint and Format

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.github/workflows/python-lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.github/workflows/python-lint.yml'

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging jobs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4
      with:
        fetch-depth: 0  # Fetch all history for better lint context

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.11'
        cache: 'pip'  # Enable built-in pip caching

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: Run Ruff Lint
      run: |
        ruff check . \
          --select E,F,D,I,N,UP,B,A,COM,C4,T20,PT,Q,RET,SIM,ERA,PL \
          --ignore D203,D213 \
          --target-version py311 \
          --fix

    - name: Run Black Formatter
      run: black .

    - name: Run Tests with Coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true

    - name: Check for remaining issues
      run: |
        ruff check . \
          --select E,F,D,I,N,UP,B,A,COM,C4,T20,PT,Q,RET,SIM,ERA,PL \
          --ignore D203,D213 \
          --target-version py311
        black --check .