name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest coverage pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Format code
        run: |
          black .
          ruff check . --fix --select E,F,D,I,N,UP,B,A,COM,C4,T20,PT,Q,RET,SIM,ERA,PL --ignore D203,D213,D101,D107,D205,D415,E501,N806,RET504,PLR2004

      - name: Create test directory
        run: |
          mkdir -p tests
          cat > tests/test_et_calculator.py << 'EOF'
          import pytest
          def test_placeholder():
              assert True
          EOF

      - name: Run tests
        run: |
          pytest tests/ --cov=./ --cov-report=xml --cov-report=term

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Commit changes
        if: github.event_name == 'pull_request'
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Apply automatic formatting" || true
          git push || true
